stages:
  - deploy

push_to_github:
  stage: deploy
  tags:
    - gitlab-to-github
  script:
    - whoami
    - cd /tmp
    - git clone --bare https://code.ihep.ac.cn/hepai/hepai.git
    - cd hepai.git
    - https_proxy=http://localhost:8118 git push --mirror https://github.com/hepaihub/hepai.git
    - cd ..
    - rm -rf hepai.git
  only:
    - main
    